# Generated by Django 5.2.7 on 2025-10-19 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('police', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='policeprofile',
            old_name='badge_no',
            new_name='region_number',
        ),
        migrations.CreateModel(
            name='PoliceStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=200, null=True)),
                ('taluka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='police_stations', to='police.taluka')),
            ],
        ),
    ]
