# Generated by Django 5.2.8 on 2025-11-29 03:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('police', '0002_rename_badge_no_policeprofile_region_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='policeprofile',
            name='last_dashboard_view',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
