# Generated by Django 5.2.7 on 2025-10-22 05:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('guardian_name', models.CharField(max_length=200)),
                ('guardian_relationship', models.CharField(max_length=100)),
                ('guardian_phone', models.CharField(max_length=20)),
                ('guardian_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('guardian_address', models.TextField()),
                ('guardian_aadhaar', models.CharField(blank=True, max_length=12, null=True)),
                ('missing_name', models.CharField(max_length=200)),
                ('missing_age', models.PositiveIntegerField(blank=True, null=True)),
                ('missing_dob', models.DateField(blank=True, null=True)),
                ('missing_gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, null=True)),
                ('missing_height', models.CharField(blank=True, max_length=50, null=True)),
                ('missing_weight', models.CharField(blank=True, max_length=50, null=True)),
                ('missing_eye_color', models.CharField(blank=True, max_length=50, null=True)),
                ('missing_hair_color', models.CharField(blank=True, max_length=50, null=True)),
                ('clothing_description', models.TextField(blank=True, null=True)),
                ('special_marks', models.TextField(blank=True, null=True)),
                ('last_seen_location', models.CharField(blank=True, max_length=255, null=True)),
                ('last_seen_date', models.DateField(blank=True, null=True)),
                ('last_seen_time', models.TimeField(blank=True, null=True)),
                ('case_type', models.CharField(choices=[('missing', 'Missing Person'), ('kidnapping', 'Kidnapping'), ('runaway', 'Runaway'), ('unknown', 'Unknown')], default='missing', max_length=20)),
                ('urgency', models.CharField(choices=[('normal', 'Normal'), ('high', 'High')], default='normal', max_length=10)),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('closed', 'Closed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('police_officer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cases', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CasePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='case_photos/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='cases.case')),
            ],
        ),
    ]
