# Generated by Django 5.2.8 on 2025-11-28 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_faceembedding'),
    ]

    operations = [
        migrations.AddField(
            model_name='casephoto',
            name='is_detection_evidence',
            field=models.BooleanField(default=False),
        ),
    ]
