# Generated by Django 5.2.8 on 2025-11-28 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_casephoto_is_detection_evidence'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='casephoto',
            options={'ordering': ['-uploaded_at']},
        ),
    ]
