# Generated by Django 5.2.8 on 2025-11-28 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0005_casephoto_latitude_casephoto_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='last_alert_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
