# Generated by Django 5.2.8 on 2025-11-29 04:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0006_case_last_alert_sent'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetectionAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_sent_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_deleted_by_officer', models.BooleanField(default=False)),
                ('is_reviewed', models.BooleanField(default=False)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='cases.case')),
                ('detection_photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cases.casephoto')),
            ],
        ),
    ]
